# Generated by Django 2.0.7 on 2020-10-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_auto_20201009_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
