# Generated by Django 2.1.15 on 2021-05-15 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_auto_20210512_1110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client',
        ),
    ]
