# Generated by Django 2.1.15 on 2021-07-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20210708_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='stock',
        ),
    ]
