# Generated by Django 2.1.15 on 2021-07-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_remove_thread_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elastic',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='velcro',
            name='stock',
        ),
    ]
