# Generated by Django 2.0.7 on 2020-09-28 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_view', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
