# Generated by Django 2.0.7 on 2020-09-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home_view', '0002_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('oname', models.CharField(max_length=100)),
                ('number', models.BigIntegerField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('bcard', models.BinaryField(max_length=100)),
                ('passwords', models.CharField(max_length=100)),
            ],
        ),
    ]
