# Generated by Django 2.0.7 on 2020-09-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_view', '0003_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
