# Generated by Django 2.0.7 on 2020-10-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_view', '0004_auto_20201001_0042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submit',
        ),
    ]
