# Generated by Django 2.1.15 on 2021-06-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_view', '0013_order_6_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_6',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_6',
            name='payment_id',
            field=models.CharField(default='Payment On Delivery', max_length=100),
        ),
    ]
